### ISSUE TITLE
When color palette is open there is no way to go back to style controls

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.morphic#100]
When palette is open it is blocking access to style controls:

<img width="527" alt="screen shot 2016-12-29 at 4 45 40 pm" src="https://cloud.githubusercontent.com/assets/467450/21557800/4f26f872-cde6-11e6-8d70-163d53714074.png">

**Comment by merryman** [comment]
Clicking on the style editor window, will now close the palette again.
538cc642a8518b28d48c01cdd61b0689a94c33c6
