### ISSUE TITLE
Multiple color palettes are open at the same time

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.morphic#101]
... and blocking each other...

<img width="620" alt="screen shot 2016-12-29 at 4 47 12 pm" src="https://cloud.githubusercontent.com/assets/467450/21557818/866eafa0-cde6-11e6-972c-a2cf3f781098.png">

**Comment by merryman** [comment]
I fixed those, and various other glitches in 538cc642a8518b28d48c01cdd61b0689a94c33c6
