### ISSUE TITLE
when opening the body styler no color chooser present

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.morphic#105]
<img width="321" alt="screen shot 2017-01-01 at 8 18 03 pm" src="https://cloud.githubusercontent.com/assets/467450/21584496/817c6c96-d05f-11e6-96ed-04b07eb1e789.png">

**Comment by rksm** [comment]
(clicking on gradient and then back to fill makes it appear)

**Comment by merryman** [comment]
Bear with me, I haven't pushed all the changes and fixes related to the style editors yet.

**Comment by rksm** [comment]
Any progress on that?

**Comment by merryman** [comment]
Should be fixed now, please update to the most recent version.

**Comment by rksm** [comment]
Thanks!
