### ISSUE TITLE
when coloring border, color is not correctly applied

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.morphic#106]
<img width="551" alt="screen shot 2017-01-01 at 8 21 14 pm" src="https://cloud.githubusercontent.com/assets/467450/21584507/f4550a5c-d05f-11e6-838d-4ebb1ac55d96.png">

I tried to make the border black but it is brownish (#663d00).

When the styler is removed full black gets applied.

**Comment by merryman** [comment]
Haha, this is actually due to the border highlighter still being active and still rendering on top of the border. Will be fixed with the updates to the style editors I am about to push.

**Comment by merryman** [comment]
Shoud be fixed now.
