### ISSUE TITLE
bounding box halo on rotation is broken

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.morphic#107]
![bounding-box-halo-issue](https://cloud.githubusercontent.com/assets/467450/21584538/9258518c-d060-11e6-9499-031de8a64f50.gif)

**Comment by rksm** [comment]
...and other transform related issues like changing the origin of a submorph moves it around

**Comment by merryman** [comment]
Are you sure your on the latest version? This bug should be fixed with 89f2f1a70c7395fd
Also the tests do cover this bug as well, and they run through for me locally as well as on travis.
