### ISSUE TITLE
GridLayout UI

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.morphic#110]
I remember being able to modify the grid of a GridLayout, adding columns and such. I can't find this anymore, how do I activate it?

**Comment by merryman** [comment]
You can edit the layouts inside the style editor (the button left to the menu that lets you select the different layouts), however the layout button kind of "falls out" of the rest of the style editors, so it is more difficult to spot.
I will try to come up with a way to edit the layouts that is more discoverable.
