### ISSUE TITLE
Multi Touch Events Cause Hand Morphs to Accumulate

### ISSUE THREAD

**Issue by merryman** [LivelyKernel/lively.morphic#111]
I observed this in chrome: When a multi touch event happens, chrome generates new pointer ids for the events in order to distinguish between the different fingers.
Currently this causes additional hand morphs to be introduced into the world, which then
remain idle at one place. These then often cause the openNearHand() calls to be compromised since they are selected as a reference point instead of the "actual" hand.
One extreme case I observed on a surface pro, where one could literary generate an additional hand morph with each time the pen touched at the world.
Apparently chrome seems to attach a completely new pointer id for every pen stroke that gets introduced to the browser.

We should probably stop distinguishing hands and halos based solely on pointer ids.

**Comment by rksm** [comment]
Thanks for checking! Yes, we need to tune a few things there. Do you know if we can figure out when a hand / pointer really disappears?

**Comment by merryman** [comment]
We can at least distinguish between touch and mouse events `pointerType == "mouse"` and only render hands for the mouse events. This fixes the problem with multiple hands when working on the desktop, however when interacting through a touch interface most of the written event code starts to error, since an existing hand is almost everywhere assumed (world, halos, etc...)
I therefore suggest, that for now we just provide the "first available hand" that is `world.firstHand` for events that are touch based.

Take a look: 9a51183

**Comment by codefrau** [comment]
I made the additional hands get removed when lifting the finger: ca86be8196c79fb3c9aef35

There was an issue when removing the last hand so I'm leaving that one in, however, that leaves an orange dot permanently on the screen. 

Maybe a better idea would be to only hide hands when a finger is lifted and re-using them on the next touch. But at least for now we do not have too may hands anymore.
