### ISSUE TITLE
GridLayout is broken after grabbing a morph from it...

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.morphic#117]
... and trying to drop it in again

![grid-layout-broken-after-grab](https://cloud.githubusercontent.com/assets/467450/22195113/2ba1f302-e0fb-11e6-8524-edc43e1b3308.gif)

@merryman

**Comment by merryman** [comment]
By now, the halo's drop interface shows the grid layouts cells and forces the user to assign the dropped morph to a certain cell.
