### ISSUE TITLE
scroll does not affect morph position / bounds

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.morphic#119]
This seems to have been introduced in the recent transform refactoring 89f2f1a70c7395fd4673cecde61a3746d9884b0f

![screen shot 2017-02-03 at 11 08 05 pm](https://cloud.githubusercontent.com/assets/467450/22616637/a5cd9a82-ea65-11e6-88c6-1d42d5a4f0fa.png)

To reproduce:

```js
import { morph } from "lively.morphic";
import { Color, pt } from "lively.graphics";
var m = morph({
  clipMode: "auto", extent: pt(100,100),
  fill: Color.red,
  scroll: pt(10,10),
  submorphs: [{
    position: pt(20,20),
    extent: pt(100,100),
    fill: Color.green,
  }]
}).openInWorld()
m.world().showHaloFor(m.submorphs[0])

```

There is actually a test that fails since the mentioned commit! `$world.execCommand("open browser", {packageName: "lively.morphic", moduleName: "tests/rendering-tests.js", textPosition: {column: 0,row: 130}});` when run locally in non-nodejs environments

**Comment by merryman** [comment]
Fixed since 7f8303b90b7cd9565a3653ee5a747333777772f1 I think.
