### ISSUE TITLE
halo items don’t obey the window bounds

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.morphic#129]
From Dan

The halo items don’t obey the window bounds, therefore you cannot read the name of large morphs, and therefore you cannot know whether you have selected, eg, the outermost morph of, eg, an object editor or style editor.  this is a real problem

**Comment by merryman** [comment]
What exactly is meant by window bounds in this case? Are we talking about the browser window? If so, halo do take into account the current browser window extent, they just do not adapt to resize events. This could however be easily added.

**Comment by rksm** [comment]
meant is scroll bars get in the way.  we currently give worlds with resizePolicy static a clipMode value of hidden which sort of fixes the problem but we might want scrollable worlds.  Tricky part is with normal scrollbars we don't know when they are visible so we might need our own scrollbars to figure this one out well.  Closing this for now until we had some time to think about scrollable worlds in general.
