### ISSUE TITLE
Halo through-click issues

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.morphic#130]
From Dan

When invoking halo, we select the innermost item first and grow outward with each subsequent click.  However right now, the parts of an inner halo (say, the label of a button) can interfere with the next cmd-click and prevent it from going to the next level.  We have to figure a way that multiple click in the same location always step outward, rather than getting stuck sometimes because of the workings of the inner halos

**Comment by merryman** [comment]
This is now fixed in lively.halos.
