### ISSUE TITLE
Styling tools inconveniently placed

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.morphic#136]
I have repeatedly the problem that the style editors get in the way.

 - Below I tried to edit the icon of a button but the "dot" of the connector is hiding the label.

![screen shot 2017-04-11 at 6 35 35 pm](https://cloud.githubusercontent.com/assets/467450/24937470/c6c8be4c-1ee5-11e7-940f-d0030d2ff459.png)

- When the style editor / color picker / etc appears it hides the view of the object it is targeting.

**Comment by rksm** [comment]
And also the resize corners hide the border when moving an object or hide small objects like here:

![screen shot 2017-04-11 at 6 50 33 pm](https://cloud.githubusercontent.com/assets/467450/24937787/ea81ef14-1ee7-11e7-9ea0-826b6849b3e8.png)

Maybe hiding them while moving an object via cursor keys or drag halo (and also when resizing via cursor keys) is an option?

**Comment by merryman** [comment]
Maybe we should consider removing the leashes that connect to the target morph again and only highlight the 'morph being styled upon request. It is after all not really possible to have multiple style  editors open at the same time. So the leashes are currently kind of pointless anyway.

On another note, it currently appears as if the inspector may become the better style editor after all. So what I will do is, to make most of the forms currently present in the style editor accessible via the inspector to change the properties (i.e. opacity, gradients and such) in a more reasonable manner.
This, combined with a more easy way to find the visual properties in question (i.e. some kind of search field that maps search terms similar to:  [filling, fill and background...] -> fill) will allow us to remove the need for a separate style editor all together.
