### ISSUE TITLE
snapping to grid always in global coordinates

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.morphic#137]
when activating snapping with alt in a submorph I would expect that it snaps to local coordinates of its owner

**Comment by merryman** [comment]
That's actually already what happens. Do you mean that the css grid does not align correctly? That's a visual thing though.

**Comment by rksm** [comment]
That's what I mean! Can this be fixed??

**Comment by rksm** [comment]
Also, can we snap the extent?

**Comment by merryman** [comment]
Is already supported since f7870ac :) will fix the alignment of the CSS grid too.
