### ISSUE TITLE
Copying morph gives timeout error

### ISSUE THREAD

**Issue by codefrau** [LivelyKernel/lively.morphic#146]
Clicking the duplicate halo handle shows the "Copy Morph" notification, but a second or so later a Timeout Error pops up.

**Comment by rksm** [comment]
Just to let you know: This is not forgotten.  It's pretty annoying to work with the clipboard "interface" here as this only allows access during a user event.  Our serialization stuff is async and sometimes accessing evt.data after serialization works and sometimes (consistently for bigger objects) it doesn't.  But we'll think of something.
