### ISSUE TITLE
filterableListPrompt kaputt!!

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.morphic#150]
![screen shot 2017-06-20 at 6 14 07 pm](https://user-images.githubusercontent.com/467450/27362595-50869afc-55e4-11e7-8947-150eb57cd094.png)

/cc @merryman

**Comment by rksm** [comment]
![filterablelistprompt-kaputt](https://user-images.githubusercontent.com/467450/27362692-fb6281d4-55e4-11e7-9cbe-2886d97f6371.gif)

**Comment by rksm** [comment]
(due to style-widgets branch merge)

**Comment by merryman** [comment]
Fixed in 9653692
