### ISSUE TITLE
[layout] how to specify a relative size and position?

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.morphic#16]
![screen shot 2016-08-10 at 10 07 23 pm](https://cloud.githubusercontent.com/assets/467450/17569057/db37cf4e-5f46-11e6-8b21-21bd626585ca.png)

When resizing the pink rectangle I want its submorphs to keep their relative positions and sizes. How can I do this with the layout system?

**Comment by merryman** [comment]
You  mean that the grid does not insist on resizing the morphs to fit to their respective boxes? I will soon add an exclusion mechanism for the grid layout, that allows to leave the extents of morphs within specific cells unattached.

**Comment by rksm** [comment]
Exclusion: Maybe a generic exclusion for other layouts as well?

Hmm, I wrote this before trying out the GridLayout. I think the GridLayout does everything I need right now. I think what we might consider is to use constraints as a different or additional layouting strategy later so that you can say this morph should maintain its size or that morph should always be a certain distance away from an edge.
