### ISSUE TITLE
[text] cmd+d throws error + freezes world

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.morphic#19]
When pressing cmd+d in the first line of the workspace in http://localhost:9001/node_modules/lively.morphic/examples/simple/index.html I get `font-metric.js:104 Uncaught TypeError: str.split is not a function` and the world stops working.

**Comment by tylervernonsmith** [comment]
Fixed by cb74d97877d1954f9938e49aa5251eb7cc77a82c
