### ISSUE TITLE
[halo] fit halo items on the screen

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.morphic#22]
When selecting a morph that is bigger than the screen (the world or the list container in a long list morph) halo items disappear. If the morph's height is larger then the screen the screen jumps to the name halo b/c it gets focus.

![halo-jump-issue](https://cloud.githubusercontent.com/assets/467450/17630700/a3e434c6-60c0-11e6-9d4a-6b21e7cd0937.gif)

**Comment by rksm** [comment]
Hmm this still doesn't work

![screen shot 2016-09-19 at 6 27 18 pm](https://cloud.githubusercontent.com/assets/467450/18654542/d250c402-7e96-11e6-8bf4-63c4f44ead01.png)

**Comment by merryman** [comment]
Is now fixed in: 600e8534733e4eb5ae743879558fde48e721e1ea
