### ISSUE TITLE
[js support] AST editing support

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.morphic#39]
- [x] highlight undefined vars
- [x] highlight syntax erros
- [x] select expressions (expand, contract based on containing expressions)
- [x] AST based navigation (fwd, bwd sexp, etc)
- [x] jumpt to definition of var
- [x] select all var refs in scope
- [x] list JS warnings and erros

**Comment by rksm** [comment]
list JS warnings and erros:

Invoke either via `Alt-x` -> List errors and warnings or via shortcut `Ctrl-C E`

(Menu support coming soon)

![js-ide-list-warnings-errors](https://cloud.githubusercontent.com/assets/467450/18653303/d4816f82-7e8d-11e6-9952-b53f67e62dd2.gif)

**Comment by rksm** [comment]
render cursors in multi selection in different sizes

![screen shot 2016-09-20 at 8 01 11 pm](https://cloud.githubusercontent.com/assets/467450/18696345/209147f0-7f6d-11e6-81a0-97c9f3c11408.png)

**Comment by levjj** [comment]
I had many good experiences using eslint to highlight errors and bad code style. Maybe it would be relatively easy to integrate eslint and benefit from [all its pre-defined rules](http://eslint.org/docs/rules/).

**Comment by rksm** [comment]
Support for AST-based editing operation is now on par with the old Lively. In particular we offer selection and navigation commands for expressions and selecting references and declarations of variables.

Shortcuts:
- select containing expression (expandRegion)
  - win: Shift-Ctrl-E`or`Ctrl-Shift-Space`
  - mac: `Shift-Command-Space` or `Ctrl-Shift-Space`
- undo select containing expression (contractRegion)
  - win: Shift-Ctrl-S`or`Ctrl-Alt-Space`
  - mac: `Ctrl-Command-space` or `Ctrl-Alt-Space`
- select containing definition (markDefun)
  - `Ctrl-Alt-h`
- forwardDownSexp
  - `Ctrl-Alt-d` or `Ctrl-Alt-Down`
- backwardUpSexp
  - `Ctrl-Alt-u` or `Ctrl-Alt-Up`
- backwardSexp
  - `Ctrl-Alt-b` or `Ctrl-Alt-Left`
- forwardSexp
  - `Ctrl-Alt-f` or `Ctrl-Alt-Right`
- Select var definition of identifier under cursor
  - `Alt-.`
- Select all references of variable under cursor
  - `Ctrl-Shift-'`
- Select next reference of variable under cursor
  - `Ctrl-Shift-[`
- Select prev reference of variable under cursor
  - `Ctrl-Shift-]`

All those commands can also be explored and activated via Run commnd (Alt-X). 

![editor-def-detection](https://cloud.githubusercontent.com/assets/467450/19588299/9979a716-9719-11e6-9c54-011066b486b4.gif)
