### ISSUE TITLE
[halos] for small morphs aren't properly spaced

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.morphic#5]
That makes them unusable

![screen shot 2016-08-07 at 2 35 22 pm](https://cloud.githubusercontent.com/assets/467450/17462413/440dc6f6-5cac-11e6-9a4b-32ebab6a0204.png)

**Comment by merryman** [comment]
Fixed in 45ef938ef2ef444d4704c6b6d1490f2c287ee74b
