### ISSUE TITLE
[rendering] scroll isn't correctly applied by renderer

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.morphic#55]
This is an issue with virtual-dom and kind of a bummer.

Lively windows can be activated, i.e. they are added in front of other morphs by using the `bringToFront()` method. What it does is to modify the submorphs array so that the active window is the last item in it. The renderer then re-renders those morphs, while doing it, it has to "move" DOM nodes around, i.e. changing the order of nodes. However, this can't be done atomically, DOM nodes have to be removed and added.

When adding a DOM node the browser internally resets the scroll of it's child nodes. Since the child nodes haven't changed themselves, virtual-dom does not consider re-rendering them and with that also does not re-apply the scroll.

So it seems that we will have to manually traverse the DOM tree when morphs are added to fix this.

**Comment by rksm** [comment]
![screen shot 2016-09-20 at 1 29 45 pm](https://cloud.githubusercontent.com/assets/467450/18688076/9abc41d2-7f37-11e6-9850-3ac8ff858997.png)

**Comment by merryman** [comment]
Just for the record, there is no way to implement scrolling entirely in Morphic, avoiding the HTML scrolling state entirely? That would be the more clean alternative compared to marking the whole morph tree that was added to a morph dirty for a render path.

**Comment by rksm** [comment]
Hmm, no I don't think that modeling the scroll manually would be wise. In order to get scroll events, DOM nodes have to actually be scrollable (CSS overflow != visible). Without scroll events we would also have to reinvent the entire scroll input event thing which on platforms like iOS isn't even possible.

**Comment by rksm** [comment]
In preparation of the fix 745e4f1 introduces a "rendering state machine" (you can wait for rendering to be done using `await morph.whenRendered()`).

rendering: we now track the rendering state more closely
- when the morph is rendered and unchanged: morph._dirty === false && morph._rendering === false
- when morph gets changed (makeDirty()): morph._dirty === true && morph._rendering === false
- when morph is about to be rendered: morph._dirty === false && morph._rendering === true
  Rendering happens asynchronously as
  1. virtual-dom creates a node tree
  2. the nodes get inserted into the actual DOM
  3. the scroll gets fixed (see issue #55)
- once rendering is done we have morph._dirty === false && morph._rendering === false again
