### ISSUE TITLE
[ui] select multiple morphs by drawing a selection rectangle

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.morphic#57]
- [x] create selection rectangle object on world drag
- [x] draw a single halo around selected morphs
- [x] make halo operations work in the context of multiple target morphs

**Comment by rksm** [comment]
@JensLincke You mentioned implementing selection rectangles in Lively4 that work for not just on the world level but also inside normal morphs. Can you explain how you solved conflicting mouse actions (submorphs might have their on onDrag / onMouseMove behaviors)?

**Comment by merryman** [comment]
A first working example can be seen in: ad968543e007f2344cd69409a15ebf16ec34c96d
Resizing and Grabbing still needs a little bit of work.
I will also take a look at how the style editor can be applied to a selection of morphs.
The halo displaying the name tag also needs a different semantic, maybe disable it altogether?

**Comment by rksm** [comment]
Maybe we can leave the name halo in, showing the names of all selected morphs and defaulting to renaming the morph whose name halo was clicked on (removing the selection). If this gets paired with undo to restore the selection I imagine it to be OK.

**Comment by merryman** [comment]
Name halo now supports multiple selected morphs: 5582febd20f17b120fd95090baf06bc5e661d8e9
