### ISSUE TITLE
Window shadow

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.morphic#7]
Window shadow currently uses dropShadow attribute, this seems wrong. How about a specific morph shadow attribute that allows to control the shadow appearance?

**Comment by merryman** [comment]
Do you suggest we replace dropShadow by a more expressive property that allows us to control the css drop shadow string more directly? i.e. shadow distance, blur factor, color and opacity?

**Comment by rksm** [comment]
Yeah, some kind of control over that would be nice. Maybe a separate shadow object similar to color? It could wrap the interface to box-shadow...?

**Comment by merryman** [comment]
I also noticed that the shadow solution we currently have still slows down the framerate considerably, when you have large objects (such as maximized windows) that are having a shadow attached. 
Well `box-shadow` we already use for the border, don't we? Plus it will not allow us to account for correctly shadowing composed morphs, or image morphs with transparency....
I wonder if going back to writing a purely morphic based shadow mechanism will solve all those things. May be worth a try.

**Comment by merryman** [comment]
Now supporting shadow objects that comprise, rotation, shadow color, distance and blur: 970951e4d1dcb20d4959984fb76b2ecc1223a317

**Comment by rksm** [comment]
Coool, I want him
![shadow](https://cloud.githubusercontent.com/assets/467450/20295029/5a1cc826-aab7-11e6-8cb3-c74fc81e4f80.jpg)
