### ISSUE TITLE
[grid layout] 

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.morphic#89]
@merryman 

window resizing breaks layout

![window-resizing-layout-bug](https://cloud.githubusercontent.com/assets/467450/19914106/3148a3cc-a065-11e6-8233-e68eee38a885.gif)

**Comment by merryman** [comment]
Was actually a problem with the window itself, for the record: 0881aca4a32b389800a428fb7afbaeaf09e1883e
