### ISSUE TITLE
[polygons] extent computation not automatic

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.morphic#90]
@merryman 

Extent of polygons does not depend on vertices.

```js
var p = new Polygon({vertices: [pt(0,0), pt(100,50), pt(50, 100)], fill: Color.orange})

p.clipMode // => visible, OK
p.extent // => pt(10.0,10.0), ????
```

extent is expected to be pt(100,100)

**Comment by merryman** [comment]
Added in: c7ca68f65e9e7b7832cc5d7ef463cf6a9ce8bb1b
Let me know if that works all right for you!

**Comment by rksm** [comment]
Awesome, thanks!
