### ISSUE TITLE
Morph selection rectangle followed by grab positions grabbed morph wrong

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.morphic#95]
![bug-1](https://cloud.githubusercontent.com/assets/467450/20441946/6aba3436-ad7b-11e6-8d81-e99e9b288026.gif)

**Comment by merryman** [comment]
These were two bugs. 
One was the previously missing grab support for selections: 04c9cd399e45edfc513f2ff729066354b0fdc2d2.
The other was due to selections being prematurely created event though just a single morph is selected: 130d899cf0ecd6b2592bf6dc14d8d83b8f9a1426.
