### ISSUE TITLE
Dragging transformed morphs moves morphs not in direction of cursor but relative to tranformation

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.morphic#96]
![bug-2](https://cloud.githubusercontent.com/assets/467450/20441991/98a446de-ad7b-11e6-9082-0421641536cb.gif)

**Comment by merryman** [comment]
Fixed in: 084ba955ee8fceeba659f55a086ad739eeb54f14.
Does however only affect the halo drag. Should we define the default drag
by means of the global transform as well?

**Comment by rksm** [comment]
Hmm, yes, I think this is more natural

**Comment by merryman** [comment]
Ok, b4ccb7d now automatically translates `dragDelta` to local owner coordinates.
