### ISSUE TITLE
Resizing via keys (Shift+Arrows) throws errors

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.morphic#97]
![bug-3](https://cloud.githubusercontent.com/assets/467450/20442019/b823e802-ad7b-11e6-9649-de9362ab3fa6.gif)

**Comment by rksm** [comment]
Also note that when expanding the error message it is positioned wrong

**Comment by merryman** [comment]
Fixed in: 57e4c1c84dee36bbf929cc0a42c2b0e4b571c52d.
The error message positioning was due to a bug in the animations fixed in: c8112beb9f2a483076d60402ed760612de8096dc
