### ISSUE TITLE
Polygon line width has weird effects

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.morphic#98]
<img width="415" alt="screen shot 2016-12-20 at 10 03 46 am" src="https://cloud.githubusercontent.com/assets/467450/21362395/11940e1e-c69d-11e6-98f0-a21a564feb83.png">

<img width="450" alt="screen shot 2016-12-20 at 10 04 05 am" src="https://cloud.githubusercontent.com/assets/467450/21362374/fa18ea2a-c69c-11e6-8a2f-5962a4898f28.png">

**Comment by merryman** [comment]
Yep, that is due to the way SVG handles borders. Will come up with a fix asap.

**Comment by merryman** [comment]
Fixed: 26590bc & 2ecc19c.
Make sure to also take a look at the cool new Gradient handles :)
